---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  sudo: false

platforms:
  - name: macosx-10.10
    driver:
      box: roboticcheese/macosx-10.10
      ssh:
        insert_key: false

suites:
  - name: default
    run_list:
      - recipe[reattach-to-user-namespace_test]
  - name: remove
    run_list:
      - recipe[reattach-to-user-namespace_test::remove]
  - name: direct
    run_list:
      - recipe[reattach-to-user-namespace_test]
    attributes:
      reattach_to_user_namespace:
        app:
          source: direct
          version: 2.4
  - name: remove_direct
    run_list:
      - recipe[reattach-to-user-namespace_test::remove]
    attributes:
      reattach_to_user_namespace:
        app:
          source: direct
          version: 2.4
